modLoader="javafml"
loaderVersion="[36,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="equipmentcompare"
version="${file.jarVersion}"
displayName="Equipment Compare"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/502561"
logoFile="icon.png"
authors="Grend"
description='''Adds additional tooltips when hovering over equipment for easy comparisons.'''

[[dependencies.equipmentcompare]]
	modId="forge"
	mandatory=true
	versionRange="[36.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5]"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.45,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="baubles"
	mandatory=false
	versionRange="[1.8.7]"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="legendarytooltips"
	mandatory=false
	versionRange="[1.3.1,)"
	ordering="NONE"
	side="BOTH"
