modLoader="javafml"
loaderVersion="[41,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="equipmentcompare"
version="${file.jarVersion}"
displayName="Equipment Compare"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/502561"
logoFile="icon.png"
authors="Grend"
description='''Adds additional tooltips when hovering over equipment for easy comparisons.'''

[[dependencies.equipmentcompare]]
	modId="forge"
	mandatory=true
	versionRange="[41.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,1.19.2]"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.1.2,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="legendarytooltips"
	mandatory=false
	versionRange="[1.4.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="curios"
	mandatory=false
	versionRange="[1.19-5.1.0.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="baubles"
	mandatory=false
	versionRange="[1.10.0.1,)"
	ordering="NONE"
	side="BOTH"
