modLoader="javafml"
loaderVersion="[39,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="equipmentcompare"
version="${file.jarVersion}"
displayName="Equipment Compare"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/502561"
logoFile="icon.png"
authors="Grend"
description='''Adds additional tooltips when hovering over equipment for easy comparisons.'''

[[dependencies.equipmentcompare]]
	modId="forge"
	mandatory=true
	versionRange="[39,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.1,1.19)"
	ordering="NONE"
	side="BOTH"

[[dependencies.equipmentcompare]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.30,)"
	ordering="NONE"
	side="BOTH"
